### ISSUE TITLE
Add Upgrade Playbook

### ISSUE THREAD

**Issue by rkruze** [redpanda-data/deployment-automation#21]
We should have a playbook on performing rolling upgrades.

**Comment by tmgstevens** [comment]
Should be fixed by #96

**Comment by WesWWagner** [comment]
What Roko intends is that we have a playbook that puts each node in maintenance mode and restarts it, one by one with adequate protections for performance/timing/etc.  Not resolved by 96.
